"""
JSON reputation responses for testing
References from apivoid.com API documentation examples.
"""
import json

basic_ip_reputation_response = """
{
   "data":{
      "report":{
         "ip":"122.226.181.165",
         "blacklists":{
            "engines":{
               "9":{
                  "engine":"Anti-Attacks BL",
                  "detected":true,
                  "reference":"https:\/\/www.anti-attacks.com\/",
                  "elapsed":"0.00"
               },
               "10":{
                  "engine":"AntiSpam_by_CleanTalk",
                  "detected":false,
                  "reference":"https:\/\/cleantalk.org\/",
                  "elapsed":"0.00"
               },
               "11":{
                  "engine":"BadIPs",
                  "detected":true,
                  "reference":"https:\/\/www.badips.com\/",
                  "elapsed":"0.00"
               },
               "12":{
                  "engine":"Bambenek Consulting",
                  "detected":false,
                  "reference":"http:\/\/www.bambenekconsulting.com\/",
                  "elapsed":"0.00"
               },
               "13":{
                  "engine":"Blacklists_co",
                  "detected":false,
                  "reference":"http:\/\/blacklists.co\/",
                  "elapsed":"0.00"
               },
               "14":{
                  "engine":"BlockList_de",
                  "detected":false,
                  "reference":"http:\/\/www.blocklist.de\/",
                  "elapsed":"0.00"
               },
               "0":{
                  "engine":"BlockedServersRBL",
                  "detected":false,
                  "reference":"https:\/\/www.blockedservers.com\/",
                  "elapsed":"0.03"
               },
               "15":{
                  "engine":"Blocklist.net.ua",
                  "detected":false,
                  "reference":"https:\/\/blocklist.net.ua\/",
                  "elapsed":"0.00"
               },
               "16":{
                  "engine":"BloggingFusion BL",
                  "detected":false,
                  "reference":"https:\/\/www.bloggingfusion.com\/",
                  "elapsed":"0.00"
               },
               "17":{
                  "engine":"Bolloms Blocked",
                  "detected":false,
                  "reference":"https:\/\/www.bolloms.com\/",
                  "elapsed":"0.00"
               },
               "18":{
                  "engine":"Booru BL",
                  "detected":false,
                  "reference":"",
                  "elapsed":"0.00"
               },
               "19":{
                  "engine":"Botvrij.eu",
                  "detected":false,
                  "reference":"http:\/\/botvrij.eu\/",
                  "elapsed":"0.00"
               },
               "20":{
                  "engine":"Brute Force Blocker",
                  "detected":false,
                  "reference":"http:\/\/danger.rulez.sk\/index.php\/bruteforceblocker\/",
                  "elapsed":"0.00"
               },
               "21":{
                  "engine":"Bytefarm_ch IP BL",
                  "detected":false,
                  "reference":"https:\/\/www.bytefarm.ch\/fail2ban\/",
                  "elapsed":"0.00"
               },
               "22":{
                  "engine":"C-APT-ure",
                  "detected":false,
                  "reference":"http:\/\/c-apt-ure.blogspot.com\/",
                  "elapsed":"0.00"
               },
               "24":{
                  "engine":"CERT-PA",
                  "detected":false,
                  "reference":"https:\/\/www.cert-pa.it\/",
                  "elapsed":"0.00"
               },
               "23":{
                  "engine":"CERT.gov.ge",
                  "detected":false,
                  "reference":"http:\/\/www.cert.gov.ge\/",
                  "elapsed":"0.00"
               },
               "25":{
                  "engine":"CI Army List",
                  "detected":false,
                  "reference":"http:\/\/cinsscore.com\/#list",
                  "elapsed":"0.00"
               },
               "28":{
                  "engine":"CSpace Hostings IP BL",
                  "detected":false,
                  "reference":"https:\/\/cspacehostings.com\/",
                  "elapsed":"0.00"
               },
               "26":{
                  "engine":"Charles Haley",
                  "detected":true,
                  "reference":"http:\/\/charles.the-haleys.org\/",
                  "elapsed":"0.00"
               },
               "27":{
                  "engine":"CruzIT Blocklist",
                  "detected":false,
                  "reference":"https:\/\/www.cruzit.com\/",
                  "elapsed":"0.00"
               },
               "29":{
                  "engine":"Cybercrime-tracker.net",
                  "detected":false,
                  "reference":"http:\/\/cybercrime-tracker.net\/index.php",
                  "elapsed":"0.00"
               },
               "31":{
                  "engine":"Darklist.de",
                  "detected":true,
                  "reference":"http:\/\/www.darklist.de\/",
                  "elapsed":"0.00"
               },
               "30":{
                  "engine":"Darren SSH Block List",
                  "detected":true,
                  "reference":"https:\/\/darrenpopham.com\/",
                  "elapsed":"0.00"
               },
               "1":{
                  "engine":"EFnet_RBL",
                  "detected":false,
                  "reference":"http:\/\/rbl.efnetrbl.org\/multicheck.php",
                  "elapsed":"0.03"
               },
               "32":{
                  "engine":"Ens160 SSH BL",
                  "detected":false,
                  "reference":"https:\/\/ens160.com\/blacklist",
                  "elapsed":"0.00"
               },
               "33":{
                  "engine":"Etnetera BL",
                  "detected":false,
                  "reference":"https:\/\/security.etnetera.cz\/",
                  "elapsed":"0.00"
               },
               "34":{
                  "engine":"FSpamList",
                  "detected":false,
                  "reference":"https:\/\/fspamlist.com\/",
                  "elapsed":"0.00"
               },
               "35":{
                  "engine":"GPF DNS Block List",
                  "detected":false,
                  "reference":"https:\/\/www.gpf-comics.com\/dnsbl\/export.php",
                  "elapsed":"0.00"
               },
               "36":{
                  "engine":"GreenSnow Blocklist",
                  "detected":false,
                  "reference":"https:\/\/greensnow.co\/",
                  "elapsed":"0.00"
               },
               "37":{
                  "engine":"HoneyDB",
                  "detected":false,
                  "reference":"https:\/\/riskdiscovery.com\/honeydb\/",
                  "elapsed":"0.00"
               },
               "2":{
                  "engine":"IBM_Cobion",
                  "detected":false,
                  "reference":"http:\/\/www-01.ibm.com\/support\/docview.wss?uid=swg21436643v",
                  "elapsed":"0.12"
               },
               "39":{
                  "engine":"IPSpamList",
                  "detected":false,
                  "reference":"http:\/\/www.ipspamlist.com\/ip-lookup\/",
                  "elapsed":"0.00"
               },
               "40":{
                  "engine":"IPsum",
                  "detected":true,
                  "reference":"https:\/\/github.com\/stamparm\/ipsum",
                  "elapsed":"0.00"
               },
               "38":{
                  "engine":"InterServer IP List",
                  "detected":false,
                  "reference":"https:\/\/sigs.interserver.net\/",
                  "elapsed":"0.00"
               },
               "41":{
                  "engine":"LAPPS Grid Blacklist",
                  "detected":false,
                  "reference":"http:\/\/www.lappsgrid.org\/",
                  "elapsed":"0.00"
               },
               "42":{
                  "engine":"LashBack UBL",
                  "detected":false,
                  "reference":"http:\/\/blacklist.lashback.com\/",
                  "elapsed":"0.00"
               },
               "43":{
                  "engine":"Liquid Binary",
                  "detected":false,
                  "reference":"https:\/\/liquidbinary.com\/",
                  "elapsed":"0.00"
               },
               "44":{
                  "engine":"Log.Onoh.Info",
                  "detected":false,
                  "reference":"http:\/\/log.onoh.info\/",
                  "elapsed":"0.00"
               },
               "48":{
                  "engine":"MKXT_NET SSH BL",
                  "detected":false,
                  "reference":"https:\/\/mkxt.net\/",
                  "elapsed":"0.00"
               },
               "45":{
                  "engine":"Malc0de",
                  "detected":false,
                  "reference":"http:\/\/malc0de.com\/database\/index.php",
                  "elapsed":"0.00"
               },
               "46":{
                  "engine":"MalwareDomainList",
                  "detected":false,
                  "reference":"http:\/\/www.malwaredomainlist.com\/",
                  "elapsed":"0.00"
               },
               "47":{
                  "engine":"Matapala_org FW Log",
                  "detected":false,
                  "reference":"https:\/\/log.matapala.org\/",
                  "elapsed":"0.00"
               },
               "3":{
                  "engine":"MegaRBL",
                  "detected":false,
                  "reference":"https:\/\/www.megarbl.net\/check",
                  "elapsed":"0.10"
               },
               "49":{
                  "engine":"Migniot SSH Bullies",
                  "detected":true,
                  "reference":"https:\/\/www.migniot.com\/",
                  "elapsed":"0.00"
               },
               "50":{
                  "engine":"Ms-ds-violation-ips",
                  "detected":false,
                  "reference":"https:\/\/github.com\/conmarap\/ms-ds-violation-ips",
                  "elapsed":"0.00"
               },
               "51":{
                  "engine":"NEU SSH Black list",
                  "detected":false,
                  "reference":"http:\/\/antivirus.neu.edu.cn\/scan\/",
                  "elapsed":"0.00"
               },
               "52":{
                  "engine":"NOC_RUB_DE",
                  "detected":false,
                  "reference":"https:\/\/noc.rub.de\/web\/",
                  "elapsed":"0.00"
               },
               "53":{
                  "engine":"NoIntegrity BL",
                  "detected":false,
                  "reference":"http:\/\/www.nointegrity.org\/",
                  "elapsed":"0.00"
               },
               "54":{
                  "engine":"NoThink.org",
                  "detected":false,
                  "reference":"http:\/\/www.nothink.org\/",
                  "elapsed":"0.00"
               },
               "4":{
                  "engine":"NordSpam",
                  "detected":false,
                  "reference":"https:\/\/www.nordspam.com\/",
                  "elapsed":"0.06"
               },
               "55":{
                  "engine":"Olegon Blocked IPs",
                  "detected":false,
                  "reference":"https:\/\/olegon.ru\/",
                  "elapsed":"0.00"
               },
               "56":{
                  "engine":"Organized Villainy Seattle Honeypot",
                  "detected":false,
                  "reference":"https:\/\/organizedvillainy.com\/",
                  "elapsed":"0.00"
               },
               "5":{
                  "engine":"PSBL",
                  "detected":false,
                  "reference":"http:\/\/psbl.org\/",
                  "elapsed":"0.02"
               },
               "57":{
                  "engine":"Peter-s NUUG IP BL",
                  "detected":false,
                  "reference":"https:\/\/home.nuug.no\/~peter\/",
                  "elapsed":"0.00"
               },
               "58":{
                  "engine":"PhishTank",
                  "detected":false,
                  "reference":"http:\/\/www.phishtank.com\/",
                  "elapsed":"0.00"
               },
               "59":{
                  "engine":"PlonkatronixBL",
                  "detected":false,
                  "reference":"http:\/\/bl.plonkatronix.com\/",
                  "elapsed":"0.00"
               },
               "60":{
                  "engine":"Ransomware Tracker",
                  "detected":false,
                  "reference":"https:\/\/ransomwaretracker.abuse.ch\/",
                  "elapsed":"0.00"
               },
               "61":{
                  "engine":"Redstout Threat IP list",
                  "detected":false,
                  "reference":"https:\/\/www.redstout.com\/index.html",
                  "elapsed":"0.00"
               },
               "62":{
                  "engine":"Reuteras Scanning Lists",
                  "detected":false,
                  "reference":"https:\/\/attackers.ongoing.today\/",
                  "elapsed":"0.00"
               },
               "63":{
                  "engine":"Ring-u NOC",
                  "detected":false,
                  "reference":"https:\/\/portal.ring-u.com\/portal\/portal.php",
                  "elapsed":"0.00"
               },
               "64":{
                  "engine":"Roquesor BL",
                  "detected":true,
                  "reference":"https:\/\/es.roquesor.com\/en\/",
                  "elapsed":"0.00"
               },
               "65":{
                  "engine":"Rutgers Drop List",
                  "detected":true,
                  "reference":"http:\/\/www.rutgers.edu\/",
                  "elapsed":"0.00"
               },
               "66":{
                  "engine":"S.S.S.H.I.A",
                  "detected":true,
                  "reference":"https:\/\/github.com\/mitchellkrogza\/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses\/",
                  "elapsed":"0.00"
               },
               "7":{
                  "engine":"S5hbl",
                  "detected":true,
                  "reference":"http:\/\/www.usenix.org.uk\/content\/rbl.html",
                  "elapsed":"0.09"
               },
               "68":{
                  "engine":"SSL Blacklist",
                  "detected":false,
                  "reference":"https:\/\/sslbl.abuse.ch\/",
                  "elapsed":"0.00"
               },
               "69":{
                  "engine":"Sblam",
                  "detected":false,
                  "reference":"http:\/\/sblam.com\/",
                  "elapsed":"0.00"
               },
               "67":{
                  "engine":"Shinmura BL",
                  "detected":false,
                  "reference":"http:\/\/www.shinmura.jp\/",
                  "elapsed":"0.00"
               },
               "8":{
                  "engine":"Spamhaus",
                  "detected":false,
                  "reference":"https:\/\/www.spamhaus.org\/lookup\/",
                  "elapsed":"0.03"
               },
               "70":{
                  "engine":"St Dominics Priory College Droplist",
                  "detected":false,
                  "reference":"https:\/\/threatintel.stdominics.sa.edu.au\/",
                  "elapsed":"0.00"
               },
               "71":{
                  "engine":"Threat Crowd",
                  "detected":false,
                  "reference":"https:\/\/www.threatcrowd.org\/",
                  "elapsed":"0.00"
               },
               "72":{
                  "engine":"Threat Sourcing",
                  "detected":false,
                  "reference":"https:\/\/www.threatsourcing.com\/",
                  "elapsed":"0.00"
               },
               "73":{
                  "engine":"URLVir",
                  "detected":false,
                  "reference":"http:\/\/www.urlvir.com\/",
                  "elapsed":"0.00"
               },
               "74":{
                  "engine":"USTC IP BL",
                  "detected":false,
                  "reference":"http:\/\/blackip.ustc.edu.cn\/",
                  "elapsed":"0.00"
               },
               "75":{
                  "engine":"VXVault",
                  "detected":false,
                  "reference":"http:\/\/vxvault.net\/ViriList.php",
                  "elapsed":"0.00"
               },
               "76":{
                  "engine":"Xtream Codes BL",
                  "detected":false,
                  "reference":"https:\/\/xtream-codes.com\/",
                  "elapsed":"0.00"
               },
               "77":{
                  "engine":"Yeuxdelibad BL",
                  "detected":false,
                  "reference":"https:\/\/yeuxdelibad.net\/",
                  "elapsed":"0.00"
               },
               "78":{
                  "engine":"ZeroDot1 Bad IPs",
                  "detected":true,
                  "reference":"https:\/\/zerodot1.gitlab.io\/CoinBlockerListsWeb\/index.html",
                  "elapsed":"0.00"
               },
               "79":{
                  "engine":"ZeuS Tracker",
                  "detected":false,
                  "reference":"https:\/\/zeustracker.abuse.ch\/",
                  "elapsed":"0.00"
               },
               "6":{
                  "engine":"realtimeBLACKLIST",
                  "detected":false,
                  "reference":"https:\/\/realtimeblacklist.com\/",
                  "elapsed":"0.10"
               }
            },
            "detections":12,
            "engines_count":80,
            "detection_rate":"15%",
            "scantime":"0.60"
         },
         "information":{
            "reverse_dns":"",
            "continent_code":"AS",
            "continent_name":"Asia",
            "country_code":"CN",
            "country_name":"China",
            "region_name":"Zhejiang",
            "city_name":"Jiaojiang",
            "latitude":28.680280685424805,
            "longitude":121.44277954101562,
            "isp":"ChinaNet Zhejiang Province Network"
         },
         "anonymity":{
            "is_proxy":false,
            "is_webproxy":false,
            "is_vpn":false,
            "is_hosting":false,
            "is_tor":false
         }
      }
   },
   "credits_remained":24.66,
   "estimated_queries":"308",
   "elapsed_time":"2.72",
   "success":true
}
"""
basic_ip_reputation_response_dict = json.loads(basic_ip_reputation_response)

basic_domain_reputation_response = """
{
   "data":{
      "report":{
         "host":"google.com",
         "domain_length":10,
         "most_abused_tld":false,
         "alexa_top_10k":true,
         "alexa_top_100k":true,
         "alexa_top_250k":true,
         "blacklists":{
            "engines":{
               "4":{
                  "engine":"AntiSocial Blacklist",
                  "detected": true,
                  "reference":"https:\/\/theantisocialengineer.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "5":{
                  "engine":"Badbitcoin",
                  "detected":false,
                  "reference":"https:\/\/badbitcoin.org\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "6":{
                  "engine":"Bambenek Consulting",
                  "detected":false,
                  "reference":"http:\/\/www.bambenekconsulting.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "8":{
                  "engine":"CERT-GIB",
                  "detected":false,
                  "reference":"http:\/\/www.cert-gib.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "9":{
                  "engine":"CERT-PA",
                  "detected":false,
                  "reference":"https:\/\/www.cert-pa.it\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "11":{
                  "engine":"CRDF",
                  "detected":false,
                  "reference":"https:\/\/threatcenter.crdf.fr\/check.html",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "7":{
                  "engine":"C_APT_ure",
                  "detected":false,
                  "reference":"http:\/\/c-apt-ure.blogspot.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "10":{
                  "engine":"CoinBlockerLists",
                  "detected":false,
                  "reference":"https:\/\/gitlab.com\/ZeroDot1\/CoinBlockerLists\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "12":{
                  "engine":"CyberCrime",
                  "detected":true,
                  "reference":"http:\/\/cybercrime-tracker.net\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "13":{
                  "engine":"DShield",
                  "detected":false,
                  "reference":"http:\/\/www.dshield.org\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "14":{
                  "engine":"EtherAddressLookup",
                  "detected":false,
                  "reference":"https:\/\/github.com\/409H\/EtherAddressLookup\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "15":{
                  "engine":"EtherScamDB",
                  "detected":false,
                  "reference":"https:\/\/etherscamdb.info\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "16":{
                  "engine":"Fumik0 Malware Tracker",
                  "detected":false,
                  "reference":"https:\/\/tracker.fumik0.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "17":{
                  "engine":"HijackedUrls",
                  "detected":false,
                  "reference":"http:\/\/www.hijackedurls.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "18":{
                  "engine":"Joewein Domain BL",
                  "detected":false,
                  "reference":"http:\/\/www.joewein.net\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "19":{
                  "engine":"Malc0de",
                  "detected":false,
                  "reference":"http:\/\/malc0de.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "20":{
                  "engine":"MalwareDomainList",
                  "detected":false,
                  "reference":"http:\/\/www.malwaredomainlist.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "21":{
                  "engine":"MalwarePatrol",
                  "detected":false,
                  "reference":"https:\/\/www.malwarepatrol.net\/",
                  "confidence":"low",
                  "elapsed":"0.00"
               },
               "22":{
                  "engine":"MetaMask EthPhishing",
                  "detected":false,
                  "reference":"https:\/\/github.com\/MetaMask\/eth-phishing-detect\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "23":{
                  "engine":"NABP Not Recommended Sites",
                  "detected":false,
                  "reference":"https:\/\/safe.pharmacy\/not-recommended-sites\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "24":{
                  "engine":"Netlab360",
                  "detected":false,
                  "reference":"http:\/\/netlab.360.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "25":{
                  "engine":"OpenPhish",
                  "detected":false,
                  "reference":"http:\/\/www.openphish.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "27":{
                  "engine":"PhishFeed",
                  "detected":false,
                  "reference":"https:\/\/phishfeed.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "28":{
                  "engine":"PhishStats",
                  "detected":false,
                  "reference":"https:\/\/phishstats.info\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "29":{
                  "engine":"PhishTank",
                  "detected":false,
                  "reference":"http:\/\/www.phishtank.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "0":{
                  "engine":"Phishing Test",
                  "detected":false,
                  "reference":"https:\/\/www.novirusthanks.org\/",
                  "confidence":"low",
                  "elapsed":"0.00"
               },
               "26":{
                  "engine":"Phishing.Database",
                  "detected":false,
                  "reference":"https:\/\/github.com\/mitchellkrogza\/Phishing.Database",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "31":{
                  "engine":"Quttera",
                  "detected":false,
                  "reference":"https:\/\/quttera.com\/home",
                  "confidence":"low",
                  "elapsed":"0.00"
               },
               "33":{
                  "engine":"RPiList Not Serious",
                  "detected":false,
                  "reference":"https:\/\/github.com\/RPiList\/specials",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "32":{
                  "engine":"Ransomware Tracker",
                  "detected":false,
                  "reference":"https:\/\/ransomwaretracker.abuse.ch\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "1":{
                  "engine":"Scam Test",
                  "detected":false,
                  "reference":"https:\/\/www.novirusthanks.org\/",
                  "confidence":"low",
                  "elapsed":"0.00"
               },
               "2":{
                  "engine":"Sinkholed Domain",
                  "detected":false,
                  "reference":"https:\/\/www.novirusthanks.org\/",
                  "confidence":"low",
                  "elapsed":"0.00"
               },
               "34":{
                  "engine":"Spam404",
                  "detected":false,
                  "reference":"https:\/\/www.spam404.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "3":{
                  "engine":"SpamhausDBL",
                  "detected":false,
                  "reference":"https:\/\/www.spamhaus.org\/lookup\/",
                  "confidence":"high",
                  "elapsed":"0.02"
               },
               "35":{
                  "engine":"SquidBlacklist (Malicious)",
                  "detected":false,
                  "reference":"https:\/\/www.squidblacklist.org\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "39":{
                  "engine":"TR-PhishingList",
                  "detected":false,
                  "reference":"https:\/\/github.com\/HorusTeknoloji\/TR-PhishingList",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "38":{
                  "engine":"Threat Sourcing",
                  "detected":false,
                  "reference":"https:\/\/www.threatsourcing.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "36":{
                  "engine":"ThreatCrowd",
                  "detected":false,
                  "reference":"https:\/\/www.threatcrowd.org\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "37":{
                  "engine":"ThreatLog",
                  "detected":false,
                  "reference":"http:\/\/www.threatlog.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "41":{
                  "engine":"URLVir",
                  "detected":false,
                  "reference":"http:\/\/www.urlvir.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "40":{
                  "engine":"URLhaus",
                  "detected":false,
                  "reference":"https:\/\/urlhaus.abuse.ch\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "43":{
                  "engine":"VXVault",
                  "detected":false,
                  "reference":"http:\/\/vxvault.net\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "42":{
                  "engine":"ViriBack C2 Tracker",
                  "detected":false,
                  "reference":"http:\/\/tracker.viriback.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               },
               "30":{
                  "engine":"precisionsec",
                  "detected":false,
                  "reference":"https:\/\/precisionsec.com\/",
                  "confidence":"high",
                  "elapsed":"0.00"
               }
            },
            "detections":2,
            "engines_count":44,
            "detection_rate":"0%",
            "scantime":"0.03"
         },
         "category":{
            "is_free_hosting":false,
            "is_anonymizer":false,
            "is_url_shortener":false,
            "is_free_dynamic_dns":false
         },
         "server":{
            "ip":"108.177.12.113",
            "reverse_dns":"ua-in-f113.1e100.net",
            "continent_code":"NA",
            "continent_name":"North America",
            "country_code":"US",
            "country_name":"United States of America",
            "region_name":"California",
            "city_name":"Mountain View",
            "latitude":37.40599060058594,
            "longitude":-122.0785140991211,
            "isp":"Google LLC"
         }
      }
   },
   "credits_remained":101003.71,
   "estimated_queries":"1,262,546",
   "elapsed_time":"0.07",
   "success":true
}
"""
basic_domain_reputation_response_dict = json.loads(basic_domain_reputation_response)
